# https://argoproj.github.io/argo-workflows/workflow-rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
rules:
  # logs get/watch are used to get the pods logs for script outputs, and for log archival
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  # Only needed if you are using ConfigMap-based cache for memoization.
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
  # This allows one workflow to create another.
  # This is only needed for resource templates.
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
  # This allows agent pod to update the taskset.
  # This is only needed for http templates.
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowtasksets/finalizers
    verbs:
      - list
      - watch
      - get
      - update
      - patch